#! /bin/bash

docker stop grafana-influxdb_con
docker rm grafana-influxdb_con

docker run -v $PWD/data:/data -d -p 80:80 -p 8083:8083 -p 8086:8086 -p 8125:8125/udp --name grafana-influxdb_con grafana_influxdb
